language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "1.0"
  - "2.0"
  - "3.0"
  - "4.0"
  - "6.0"
  - "node"
sudo: false
script: npm test
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8